name: Build and test Go
on: [push, pull_request]
jobs:
  lint:
    name: Linting format and golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Format Check
        run: test -z "$(gofmt -l .)"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          verbose: true
          flags: unittests